#!/bin/bash

# CREATE GROUP AND DIRECTORIES
groupadd -f g_admin  # -f will avoid raising an error if group already exist
groupadd -f g_user
groupadd -f g_author
groupadd -f g_mod

yamlFile="/config/users.yaml"

# CREATE USERS, HOME DIR, ASSIGN GROUPS, SUB DIR

for u in $(yq -e -r '.users[].username' $yamlFile);do 
    if ! id "$u" &> /dev/null;then
        mkdir -p "/home/users"
        useradd -m -d "/home/users/$u" "$u"  #-m creates home -d sets it explictly to specified value
        usermod -g g_user "$u" #-g specifies the new primary group -G for secondary group
        mkdir -p "/home/users/$u/allBlogs" #-p includes necessary parent directories
        setfacl -R -m u:$u:rwx /home/users/$u;  # permission for all exixting files
        setfacl -R -d -m u:$u:rwx /home/users/$u;  # permission for all new files
    fi
done

for u in $(yq -e -r '.authors[].username' $yamlFile);do 
    if ! id "$u" &> /dev/null;then
        mkdir -p "/home/authors"
        useradd -m -d "/home/authors/$u" "$u"
        usermod -g g_author "$u"
        mkdir -p "/home/authors/$u/blogs"
        mkdir -p "/home/authors/$u/public"
        setfacl -R -m u:$u:rwx /home/authors/$u # users and authors have permissions to their home dir. -m to modify
        setfacl -R -d -m u:$u:rwx /home/authors/$u; #-d for new files -R for all existing files and folders inside
    fi
done

for u in $(yq -e -r '.mods[].username' $yamlFile);do 
    if ! id "$u" &> /dev/null;then
        mkdir -p /home/mods
        useradd -m -d "/home/mods/$u" "$u"
        usermod -g g_mod "$u"
        setfacl -R -m u:$u:rwx /home/mods/$u; 
        setfacl -R -d -m u:$u:rwx /home/mods/$u;

    fi
done

for u in $(yq -e -r '.admins[].username' $yamlFile);do 
    if ! id "$u" &> /dev/null;then
        mkdir -p /home/admins
        useradd -m -d "/home/admins/$u" "$u"
        usermod -g g_admin "$u"
        setfacl -R -m u:$u:rwx /home; 
        setfacl -R -d -m u:$u:rwx /home; 
    fi
done

# ASSIGN AUTHORS TO RESPECTIVE MODS 

for mod in $(yq -e -r '.mods[].username' $yamlFile);do # -e exits code if there is some error in yq. -r returns raw output not containing inverted commas
    for author in $(yq -e -r ".mods[] | select(.username == \"$mod\") | .authors[]" $yamlFile); do
        setfacl -d -m u:$mod:rw "/home/authors/$author/public" # -d to add same acl to all new files and foldes inside
    done
done

# LISTING PUBLIC DIR OF AUTHORS TO ALL USERS

for user in $(yq -e -r '.users[].username' $yamlFile);do 
    for author in $(yq -e -r '.authors[].username' "$yamlFile");do
        setfacl -m u:"$user":r "/home/authors/"$author"/public"
        ln -s "/home/authors/"$author"/public" "/home/users/"$user"/allBlogs/"$author""  # mainfile first
    done
done




